build-presentation: 
	pandoc -t revealjs transformers-and-llms.md -s -o transformers-and-llms.html \
		--highlight-style=breezedark \
		--css=custom.css \
		--slide-level=3 \
		--variable theme=solarized 
