build-presentation: 
	pandoc -t revealjs presentation.md -s -o presentation.html \
		--highlight-style=breezedark \
		--mathjax \
		--css=custom.css \
		--slide-level=3 \
		--variable theme=solarized
